version: '3.8'

services:
  mongo:
    image: mongo:5.5.0
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:6.6.0.RELEASE
    container_name: redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5.28.5
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"

  postgres:
    image: postgres:42.7.5
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"