services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5.12  # Versión confirmada que existe
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_connector_bolt_enabled="true"
      - NEO4J_dbms_connector_bolt_tls__level=DISABLED
    ports:
      - "7474:7474"
      - "7687:7687"